--test
CREATE TABLE ALUNOS
(
  nroMatricula VARCHAR(10) NOT NULL,
  cpf VARCHAR(10) NOT NULL,
  email VARCHAR(100) NOT NULL,
  nome VARCHAR(150) NOT NULL,
  anoIngresso NUMBER(4) NOT NULL,
  endereco VARCHAR(150) NULL,
  sexo CHAR(1) NOT NULL,
  
  CONSTRAINT PK_ALUNOS PRIMARY KEY (nroMatricula),
  CONSTRAINT AK1_ALUNOS UNIQUE (cpf),
  CONSTRAINT AK2_ALUNOS UNIQUE (email)
);

SELECT * FROM ALUNOS;

INSERT INTO ALUNOS (NROMATRICULA, CPF, EMAIL, NOME, ANOINGRESSO, ENDERECO, SEXO)
VALUES
(
'18111219', '123456', 'RAFAEL.RLS70@GMAIL.COM', 'RAFAEL', 2018, NULL , 'M'
);

INSERT INTO ALUNOS (NROMATRICULA, CPF, EMAIL, NOME, ANOINGRESSO, ENDERECO, SEXO)
VALUES
(
'19704513', '457812', 'wololo@wolo.wol', 'JUAO', 2017, NULL , 'M'
);

INSERT INTO ALUNOS (NROMATRICULA, CPF, EMAIL, NOME, ANOINGRESSO, ENDERECO, SEXO)
VALUES
(
'18203013', '978456', 'IELELE@IELE.IE', 'JUOA', 2019, NULL , 'F'
);

INSERT INTO ALUNOS (NROMATRICULA, CPF, EMAIL, NOME, ANOINGRESSO, ENDERECO, SEXO)
VALUES
(
48111219, 978458, 'FAFAEL.RLS70@GMAIL.COM', 'RAFAEL', 2018, NULL , 'M'
);

ALTER TABLE ALUNOS
ADD CONSTRAINT CK_ANOINGRESSO CHECK (ANOINGRESSO > 2000);

ALTER TABLE ALUNOS
ADD CONSTRAINT CK_SEXO CHECK (sexo IN ('M', 'F'));

INSERT INTO ALUNOS (NROMATRICULA, CPF, EMAIL, NOME, ANOINGRESSO, ENDERECO, SEXO)
VALUES
(
48111247, 778458, 'FAFAEL.RLS70@yobobo.lul', 'RAFAEL', 2018, NULL , 'M'
);

CREATE TABLE ESTADOS
(
  uf CHAR(2) NOT NULL,
  nome VARCHAR2(40) NOT NULL,
  regiao CHAR(2) NOT NULL,
  
  CONSTRAINT PK_ESTADOS PRIMARY KEY (uf)
);

CREATE TABLE CIDADES
(
  cod_cidade NUMBER(4) NOT NULL,
  nome VARCHAR2(60) NOT NULL,
  uf CHAR(2) NOT NULL,
  
  CONSTRAINT PK_CIDADES PRIMARY KEY (cod_cidade)
);

INSERT INTO CIDADES
VALUES 
(9784, 'BENGALANDIA', 'XX');

INSERT INTO ESTADOS
VALUES 
('RS', 'RIO GRANDE DO CACETE', 'CT');

DELETE FROM CIDADES
WHERE UF = 'CT';

INSERT INTO CIDADES
VALUES 
(9784, 'BENGALANDIA', 'RC');

UPDATE ESTADOS
SET UF = 'RC'
WHERE UF = 'RS';

SELECT * FROM ESTADOS;

SELECT * FROM CIDADES;

ALTER TABLE CIDADES
ADD
(
  CONSTRAINT FK_EST_CID
    FOREIGN KEY (UF)
    REFERENCES ESTADOS (UF)
);


INSERT INTO CIDADES
VALUES 
(9784, 'TIFUDEL', 'XX');